
INSERT INTO GIFT (ID, NAME) VALUES (1, 'Cash');
INSERT INTO GIFT (ID, NAME) VALUES (2, 'Mobile');
INSERT INTO GIFT (ID, NAME) VALUES (3, 'Car');


INSERT INTO GROUPS (ID, GIFT_ID) VALUES (1, 1);
INSERT INTO GROUPS (ID, GIFT_ID) VALUES (2, 2);
INSERT INTO GROUPS (ID, GIFT_ID) VALUES (3, 3);
INSERT INTO GROUPS (ID, GIFT_ID) VALUES (4, 0);
